dist: trusty
language: generic
services:
  - docker
branches:
  only:
    - master
install:
  - source ci/install.sh
script:
  - bash build/build.sh
cache:
  directories:
    - ci/cache
deploy:
  provider: script
  script: bash -o xtrace ci/deploy.sh
  skip_cleanup: false
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = "push"
